version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=180000
      - GRID_TIMEOUT=180000
    networks:
      - grid

  chrome-node:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    networks:
      - grid

networks:
  grid:
